[alias]
html    = "r -p cargo-html -- html"
b       = "run -p xtask -- build"
c       = "run -p xtask -- check"
d       = "run -p xtask -- doc"
r       = "run -p xtask -- run"

[target.'cfg(windows)']
rustflags = ["-C", "target-feature=+crt-static"]
