# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members                 = ["*/"]
exclude                 = ["target/"]

[profile.release]
debug                   = 0
lto                     = true
opt-level               = "z"
panic                   = "abort"
