name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Info
      run: |
        rustc -V
        cargo -V
    - name: Test
      run: cargo test --all-features
