name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Info
      run: |
        rustc -V
        cargo -V
    - name: Dependencies
      run: |
        rustup target add wasm32-wasi
        rustup target add wasm32-unknown-unknown
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        curl -L https://github.com/koute/cargo-web/releases/download/0.6.20/cargo-web-x86_64-unknown-linux-gnu.gz | gzip -d > ~/.cargo/bin/cargo-web
        chmod +x ~/.cargo/bin/cargo-web
    - name: Build
      run: cargo b
