name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          /home/runner/.wasm-pack
          /home/runner/.cargo/bin
          /home/runner/.cargo/.crates.toml
          /home/runner/.cargo/.crates2.json
        key: ${{ runner.os }}-${{ hashFiles('**/tools.rs') }}
    - name: Info
      run: |
        rustc -V
        cargo -V
    - name: Dependencies
      run: |
        rustup target add wasm32-wasi
        rustup target add wasm32-unknown-unknown
        cargo install wasm-pack
        cargo install cargo-web
        wasm-pack --version
        cargo web --version
    - name: Build
      run: cargo b
